# Generated by Django 4.2.18 on 2025-02-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='state',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
